# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SnilsPageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 304)
        self.label_image = QtWidgets.QLabel(Dialog)
        self.label_image.setGeometry(QtCore.QRect(20, 20, 421, 261))
        self.label_image.setObjectName("label_image")
        self.label_snils = QtWidgets.QLabel(Dialog)
        self.label_snils.setGeometry(QtCore.QRect(470, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_snils.setFont(font)
        self.label_snils.setObjectName("label_snils")
        self.snils = QtWidgets.QLineEdit(Dialog)
        self.snils.setGeometry(QtCore.QRect(470, 120, 241, 31))
        self.snils.setObjectName("snils")
        self.button_add = QtWidgets.QPushButton(Dialog)
        self.button_add.setGeometry(QtCore.QRect(470, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "СНИЛС"))
        self.label_image.setText(_translate("Dialog", "TextLabel"))
        self.label_snils.setText(_translate("Dialog", "СНИЛС"))
        self.button_add.setText(_translate("Dialog", "Добавить"))
